version: '2'
services:
  renren-admin:
    image: renren/renren-admin
    ports:
    - "9080:8080"
    environment:
    - spring.profiles.active=dev
  renren-api:
    image: renren/renren-api
    ports:
    - "9081:8081"
    environment:
    - spring.profiles.active=dev